- key: home
  es: /
  ca: /ca/
  en: /en/
- key: about
  es: /sobre-mi/
  ca: /ca/sobre-mi/
  en: /en/about/
- key: services
  es: /servicios/
  ca: /ca/serveis/
  en: /en/services/
- key: faq
  es: /informacion-util/
  ca: /ca/informacio-util/
  en: /en/faq/
- key: contact
  es: /contacta/
  ca: /ca/contacta/
  en: /en/contact/
- key: legal
  es: /legal/
  ca: /ca/legal/
  en: /en/legal/
- key: individual-therapy
  es: /servicios/terapia-individual/
  ca: /ca/serveis/terapia-individual/
  en: /en/services/individual-therapy/
- key: couples-therapy
  es: /servicios/terapia-de-pareja/
  ca: /ca/serveis/terapia-de-parella/
  en: /en/services/couples-therapy/
- key: online-therapy
  es: /servicios/terapia-online/
  ca: /ca/serveis/terapia-online/
  en: /en/services/online-therapy/
- key: parenting-support
  es: /servicios/apoyo-a-la-crianza/
  ca: /ca/serveis/suport-a-la-crianca/
  en: /en/services/parenting-support/
- key: special-needs-support
  es: /servicios/apoyo-a-familiares-nnee/
  ca: /ca/serveis/suport-a-familiars-nnee/
  en: /en/services/support-for-family-members-of-children-with-special-needs/
- key: workshops
  es: /servicios/asesoramientos-y-talleres/
  ca: /ca/serveis/assessorament-i-tallers/
  en: /en/services/consultations-and-workshops/
